---

########################################
## CONFIG | Global Variables
########################################
global:
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: true
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: True
  AIRFLOW__CORE__EXECUTOR: DaskExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2//airflowairflow@airflow-db/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2//airflowairflow@airflow-db/airflow
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: False
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
  AIRFLOW__DASK__CLUSTER_ADDRESS: tcp//dask-scheduler-airflow8786
  ARCHIVE_DB_USER: yugabyte
  ARCHIVE_DB_PASSWORD: yugabyte
  ARCHIVE_DB_HOSTNAME: archive-db
  ARCHIVE_DB_PORT: 5433
  ARCHIVE_DB_DATABASE: archive_db
  META_DB_USER: meta_data
  META_DB_PASSWORD: meta_data
  META_DB_HOSTNAME: meta-data-db
  META_DB_PORT: 5432
  DLM_DB_USER: locking
  DLM_DB_PASSWORD: locking
  DLM_DB_HOST: locks_db
  DLM_DB_DATABASE: distributed_locking
  NATS_SERVER_URL: nats//godon_nats_14222
  DASK_OPTUNA_SCHEDULER_URL: dask-scheduler-optuna8786
    #PROMETHEUS_URL: http//prometheus9090


########################################
## Component | Dask Cluster for Distributed Metaheuristics Processing
########################################
dask:
  enabled: true

  ## The Dask entrypoint is the scheduler
  scheduler:
    name: Optuna-Dask-Scheduler
    enabled: true
    image:
      repository: "ghcr.io/dask/dask" # Container image repository.
      tag: "2023.12.1" # Container image tag.
      pullPolicy: IfNotPresent # Container image pull policy.
    servicePort: 8786

  ## The Dask Workers
  worker:
    name: Optuna-Dask-Worker # Dask worker name.
    image:
      repository: "ghcr.io/dask/dask" # Container image repository.
      tag: "2023.12.1" # Container image tag.
      pullPolicy: IfNotPresent # Container image pull policy.
    replicas: 3

########################################
## Component | Postgres Based Distributed Locking Database
########################################
locking-db:
  image:
    repository: "docker.io/postgres/postgres/"
    tag: 13
    pullPolicy: IfNotPresent

  auth:
    username: locking
    password: locking
    database: locking

metadata-db:
  image:
    repository: "docker.io/postgres/postgres/"
    tag: 13
    pullPolicy: IfNotPresent

  auth:
    username: meta_data
    password: meta_data
    database: meta_data

archive-db:
  image:
    repository: "docker.io/yugabytedb/yugabyte"
    tag: 2.18.1.0-b84
    pullPolicy: IfNotPresent

  replicas:
    master: 3
    tserver: 3

  master:
    extraEnv:
      - name: YSQL_DB
        value: archive-db

########################################
## CONFIG | Nats Queueing System
########################################
nats:
  container:
    image:
      repository: nats
      tag: nats:2.9.15
  nats:
    port: 4222
    tls:
      enabled: false
  monitor:
    enabled: true
    port: 8222
    tls:
      enabled: false
