remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - stable=https://charts.helm.sh/stable
  - dask=https://helm.dask.org/
  - postgres=https://charts.bitnami.com/bitnami
  - yugabyte=https://charts.yugabyte.com
  - nats=https://nats-io.github.io/k8s/helm/charts
  - airflow=oci://ghcr.io/cherusk/airflow
helm-extra-args: --timeout=600s
