---
## Service as entrypoint to API
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-api"  (include "godon.fullname" .) | trunc 58 | quote }}
  labels:
    service-type: "api-endpoint"
spec:
  type: "ClusterIP"
  ports:
    - protocol: TCP
      name: "api-port"
      port: {{ .Values.api.port }}
  selector:
    app.kubernetes.io/name: {{ include "godon.fullname" . }}-api
