name: "run chart tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  lint_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.10.1

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.0
        with:
          version: v3.10.1

      - name: List Changed Charts (chart-testing)
        id: list-changed
        run: |
          CHANGED=$(ct list-changed --config chart-testing-config.yaml)
          if [[ -n "$CHANGED" ]]; then
            echo "::set-output name=CHANGED::true"
          fi

      - name: Lint Charts (chart-testing)
        if: ${{ steps.list-changed.outputs.CHANGED == 'true' }}
        run: |
          ct lint --config chart-testing-config.yaml --check-version-increment=false

      - name: Create kind Cluster
        # specific commit is used because no tagged version includes `kubectl_version` feature
        uses: helm/kind-action@v1.8.0
        if: ${{ steps.list-changed.outputs.CHANGED == 'true' }}
        timeout-minutes: 5
        with:
          version: v0.20.0
          kubectl_version: v1.26.4
          node_image: kindest/node:v1.29.0@sha256:54a50c9354f11ce0aa56a85d2cacb1b950f85eab3fe1caf988826d1f89bf37eb
          wait: 300s

      - name: Install Charts (chart-testing)
        if: ${{ steps.list-changed.outputs.CHANGED == 'true' }}
        run: |
          ct install --config chart-testing-config.yaml
